replicaCount: 1

image:
  repository: ghcr.io/mlops-for-all/mlflow-server
  tag: 3.7-1.22.0-v1.0.0
  pullPolicy: IfNotPresent

db:
  # backendStoreUri: postgresql://<DB_USER>:<DB_PASSWD>@<POSTGRESQL_HOST>:<POSTGRESQL_PORT>/<DB_SCHEMA_NAME>
  backendStoreUri: postgresql://mlflow:mlflow@postgresql-mlflow-service.mlflow-system.svc.cluster.local:5432/mlflow

s3:
  endpointUrl: http://minio-service.kubeflow.svc.cluster.local:9000
  accessKeyId: minio
  secretAccessKey: minio123
  bucket: mlflow

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
